name: GitHub Actions Demo
on: [push]
push:
  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps: 
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: npm install
    - name: Run prod project
      run: npm run build:prod
    - name: linting ts
      run: npx eslint . --fix
    - name: linting scss
      run: npx stylelint '**/*.scss' --fix
    - name: run test unit
      run: npm run unit
    - name: build storybook
      run: npm run storybook:build
    - name: screenshot testing
      run: npm run test:ui:ci
